[package]
name = "fractales"
version = "0.1.0"
authors = ["jules"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.0"
num-complex = "0.2.3"
num-integer = "0.1.41"
GSL = "0.4"
rayon = "1.1"
